server:
  port: 8091
  servlet:
    context-path: /p/user

spring:
  application:
    name: web-user
  profiles:
    active:
      - config
      - service


knife4j:
  enable: true
  basic:
    username: root
    password: root
    enable: true
  setting:
    language: zh-CN

jwt:
  secret: RYSJWTTOKEN


