server:
  port: 8092
  servlet:
    context-path: /p/admin

spring:
  application:
    name: web-admin
  profiles:
    active:
      - config
      - service


knife4j:
  enable: true
  basic:
    username: root
    password: root
    enable: true
  setting:
    language: zh-CN

jwt:
  secret: RONGYISHOUJWTTOKEN

